### ISSUE TITLE
Cannot download RAP file

### ISSUE THREAD

**Issue by vrodriguezf** [evertonstz/pynps#22]
I am donwloading a PS3 game directly into a external USB drive and I am having this error. Any ideas?

```
--------------------------------------------------------------------------------------------------------------------------
[DOWNLOAD] Batman Arkham Origins (EU) [NPEB01414] for PS3
OmyVmsLhSkcJEZlLcSDGIwwawjOIbV 100%[==================================================>]  14,08G  11,2MB/s    in 27m 39s 
--------------------------------------------------------------------------------------------------------------------------
[CHECKSUM] No checksum provided by NPS, skipping check
--------------------------------------------------------------------------------------------------------------------------
[EXTRACTION] skipping extraction since pkg2zip doesn't work with pkg2zip
--------------------------------------------------------------------------------------------------------------------------
[MOVE] PS3 pkg file moved to: /media/victor/PS3external/pyNPS/PS3/GAMES/packages/Batman Arkham Origins (EU) - EP1018-NPEB01414_00-BATMANORIGINS001.pkg
[MOVE] attempting to delete .pkg file from old location
[MOVE] success, the compressed .pkg was deleted
--------------------------------------------------------------------------------------------------------------------------
[RAP] downloaing RAP file
E94D3BCCFF0A5A60A8E4E4F1D6B049 100%[==================================================>]      16  --.-KB/s    in 0s      
Traceback (most recent call last):
  File "/home/victor/.local/bin/pynps", line 11, in <module>
    sys.exit(cli_main())
  File "/home/victor/.local/lib/python3.7/site-packages/pynps/cli/cli.py", line 715, in cli_main
    get_rap(i, WGET, rap_folder, rap_url)
  File "/home/victor/.local/lib/python3.7/site-packages/pynps/functions/functions.py", line 262, in get_rap
    os.rename(f"{dl_tmp_folder}{i['RAP']}", rap_folder)
OSError: [Errno 18] Invalid cross-device link: '/tmp/tmpjqo89k69/E94D3BCCFF0A5A60A8E4E4F1D6B0499D' -> '/media/victor/PS3external/pyNPS/PS3/GAMES/exdata/EP1018-NPEB01414_00-BATMANORIGINS001.rap'
```

**Comment by evertonstz** [comment]
Yes, os.rename() only works when the source and destination are on the same filesystem, therefore you can only download into your computer. I'll solve this problem next release since there's a pretty simple solution for this problem, totally forgot this was a thing.

**Comment by vrodriguezf** [comment]
awesome, thank you for the prompt reply!!!
