### ISSUE TITLE
[Errno 36] File name too long

### ISSUE THREAD

**Issue by jeffrey-lebowski** [evertonstz/pynps#31]
I get the following error for _3) PS3 | NPUB30314 | USA | Game | Dead Space Extraction_ . The rap file never appears where it's supposed to.
<details>
<summary>output</summary>

```
me@mypc:~/Downloads/pyNPS/PS3# pynps -G -c ps3 "Dead Space Extraction"

[PKG2ZIP] you don't have a valid pkg2zip installation or binary in your system, extraction will be skipped. PS3 games don't need pkg2zip
-------------------------------------------------------------------------------------------------------------------------------------------------------------

[SEARCH] here are the matches:
1) PS3 | NPEB00318 | EUR | Game | Dead Space Extraction (Trial to Full)                                                                           [3.447 GiB]

2) PS3 | NPUB30314 | USA | Game | Dead Space Extraction                                                                                           [3.464 GiB]

3) PS3 | NPUB30314 | USA | Game | Dead Space Extraction                                                                                           [3.464 GiB]

Enter the number for what you want to download, you can enter multiple numbers using commas: 3
-------------------------------------------------------------------------------------------------------------------------------------------------------------

[SEARCH] you're going to download the following files:
3) PS3 | NPUB30314 | USA | Game | Dead Space Extraction                                                                                           [3.464 GiB]

Download files? [y/n]: y
-------------------------------------------------------------------------------------------------------------------------------------------------------------

[DOWNLOAD] Dead Space Extraction (US) [NPUB30314] for PS3
zZyBxuyRDPGzGCrzuxCqEUFvplMyLZsMphAGCpl 100%[============================================================================>]   3.46G  95.1MB/s    in 39s
-------------------------------------------------------------------------------------------------------------------------------------------------------------

[CHECKSUM] No checksum provided by NPS, skipping check
-------------------------------------------------------------------------------------------------------------------------------------------------------------

[EXTRACTION] skipping extraction since pkg2zip doesn't work with pkg2zip
-------------------------------------------------------------------------------------------------------------------------------------------------------------

[MOVE] PS3 pkg file moved to: /home/username12345/Downloads/pyNPS/PS3/GAMES/packages/Dead Space Extraction (US) - UP0006-NPUB30314_00-DSEXTRACTIONKEY1.pkg
[MOVE] attempting to delete .pkg file from old location
[MOVE] success, the compressed .pkg was deleted
-------------------------------------------------------------------------------------------------------------------------------------------------------------

[RAP] downloaing RAP file
4e5044000000000300000003000000005550303 100%[============================================================================>]     352  --.-KB/s    in 0s
Traceback (most recent call last):
  File "/usr/local/bin/pynps", line 33, in <module>
    sys.exit(load_entry_point('pynps==1.6.2', 'console_scripts', 'pynps')())
  File "/usr/local/lib/python3.6/dist-packages/pynps-1.6.2-py3.6.egg/pynps/cli/cli.py", line 727, in cli_main
    get_rap(i, WGET, rap_folder, rap_url)
  File "/usr/local/lib/python3.6/dist-packages/pynps-1.6.2-py3.6.egg/pynps/functions/functions.py", line 277, in get_rap
    copyfile(f"{dl_tmp_folder}{i['RAP']}", rap_folder)
  File "/usr/lib/python3.6/shutil.py", line 120, in copyfile
    with open(src, 'rb') as fsrc:
OSError: [Errno 36] File name too long: '/tmp/tmp5r3rymwv/4e5044000000000300000003000000005550303030362d4e50554233303331345f30302d445345585452414354494f4e4b455931000000000000000000000000476c6f72794f664272756e6573747564dadac5ce3234df54702a451a970faa39af0bf3c53b1ac16e5286d3457872eb1e000000000000000000000000000000000000000c0000400000000000000000408598216d2c40548905889dd0e44ae5125fe6242c087ce197ada23c2d85ad2e710000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000d4beebd71f9c53a30699e98e969e45e7dd32a9679cffc126e47db2ecbc3e454f1698d0d0cd7ba63504fe17a7ced68fd0558fbe366a116de61355a79a0fb786825eb10a135fbeef61731fb212bc9ff4b1454441544120332e332e302e57000000'
```

</details>
<details>
<summary>specs</summary>

```
Ubuntu 18.04.6 LTS
Linux 5.4.0-1058-gcp
pynps version 1.6.1
```

</details>

**Comment by garar** [comment]
Hi!

I get the same error for the same game:

```
[RAP] downloaing RAP file
4e50440000000003000000030000000055503030303 100%[========================================================================================>]     352  --.-KB/s    in 0s      
Traceback (most recent call last):
  File "/home/garar/.local/bin/pynps", line 8, in <module>
    sys.exit(cli_main())
  File "/home/garar/.local/pipx/venvs/pynps/lib/python3.8/site-packages/pynps/cli/cli.py", line 727, in cli_main
    get_rap(i, WGET, rap_folder, rap_url)
  File "/home/garar/.local/pipx/venvs/pynps/lib/python3.8/site-packages/pynps/functions/functions.py", line 277, in get_rap
    copyfile(f"{dl_tmp_folder}{i['RAP']}", rap_folder)
  File "/home/garar/miniconda3/lib/python3.8/shutil.py", line 261, in copyfile
    with open(src, 'rb') as fsrc, open(dst, 'wb') as fdst:
OSError: [Errno 36] File name too long: '/tmp/tmpqoyghnmq/4e5044000000000300000003000000005550303030362d4e50554233303331345f30302d445345585452414354494f4e4b455931000000000000000000000000476c6f72794f664272756e6573747564dadac5ce3234df54702a451a970faa39af0bf3c53b1ac16e5286d3457872eb1e000000000000000000000000000000000000000c0000400000000000000000408598216d2c40548905889dd0e44ae5125fe6242c087ce197ada23c2d85ad2e710000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000d4beebd71f9c53a30699e98e969e45e7dd32a9679cffc126e47db2ecbc3e454f1698d0d0cd7ba63504fe17a7ced68fd0558fbe366a116de61355a79a0fb786825eb10a135fbeef61731fb212bc9ff4b1454441544120332e332e302e57000000'
```
